---
#-------------------------------
# General Site Settings

title: Decovac
logo:
author: Fiocruz
description: Ecossistema baseado em dados do Brasil e do Paquistão para vigilância de vacinas contra a Covid-19
email: vinicius.oliveria@fiocruz.br
phone: 
address: Parque Tecnológico da Edf. Tecnocentro, R. Mundo, 121 - sala 315 - Trobogy, Salvador - BA, 41745-715
copyright: Copyright &copy; 2025 

menu:
  - { name: Sobre, link: "/sobre" }
  - { name: Resultados, link: "/resultados" }
  - { name: Lições Aprendidas, link: "/licoes" }
  - { name: Publicações, link: "/publicacoes" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Ecossistema baseado em dados do Brasil e do Paquistão <br> para vigilância de vacinas contra a Covid-19

# social:
#  - { icon: "ti-facebook", link: "#" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: O intuito deste projeto é desenvolver uma estrutura para reutilizar grandes conjuntos de dados clínicos e administrativos que vão permitir a análise comparativa da segurança e eficácia da vacina da Covid-19 no Brasil e no Paquistão. Nesse sentido, trata-se de uma iniciativa que promoverá evidências baseadas em dados do Sul Global.

blurb-btn-link: "/sobre"
blurb-btn-name: Saiba mais

